baseURL = "https://eturkes.com/"
title = "Website of Emir Turkes"
copyright = "© 2025-2026 Emir Turkes"
languageCode = "en-us"
theme = "origin"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[pagination]
pagerSize = 10

[params]
  description = "PhD graduate from UCL researching neurodegenerative disease using bioinformatic methods"
  featured = true

  [params.socials]
    x = "https://x.com/EmirTurkes1"
    github = "https://github.com/eturkes"
    linkedin = "https://www.linkedin.com/in/eturkes/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 5

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "publications"
    name = "Publications"
    url = "/post/"
    weight = 20

  [[menu.main]]
    identifier = "get-started"
    name = "Get Started"
    url = "/get-started/"
    weight = 25

  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/media/emir-turkes-cv.pdf"
    weight = 30

[taxonomies]
  category = "categories"
  tag = "tags"

[markup]
  [markup.highlight]
    style = "github"
    tabWidth = 4

  [markup.goldmark.renderer]
    unsafe = true
